
#██╗░░██╗░█████╗░██╗░░██╗░█████╗░███╗░░██╗██╗░██╗░░░░░░░██╗░█████╗░  ░█████╗░░█████╗░██████╗░███████╗
#██║░░██║██╔══██╗██║░██╔╝██╔══██╗████╗░██║██║░██║░░██╗░░██║██╔══██╗  ██╔══██╗██╔══██╗██╔══██╗██╔════╝
#███████║███████║█████═╝░██║░░██║██╔██╗██║██║░╚██╗████╗██╔╝███████║  ██║░░╚═╝██║░░██║██████╔╝█████╗░░
#██╔══██║██╔══██║██╔═██╗░██║░░██║██║╚████║██║░░████╔═████║░██╔══██║  ██║░░██╗██║░░██║██╔══██╗██╔══╝░░
#██║░░██║██║░░██║██║░╚██╗╚█████╔╝██║░╚███║██║░░╚██╔╝░╚██╔╝░██║░░██║  ╚█████╔╝╚█████╔╝██║░░██║███████╗
#╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝░╚════╝░╚═╝░░╚══╝╚═╝░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝  ░╚════╝░░╚════╝░╚═╝░░╚═╝╚══════╝

#建築できる最大範囲(半径)
range: 2